vehicle:
  type: Truck
  initial_speed: 80

timeseries:  
  minutes: 360
  min_minutes: 60

anomaly:
  type: WheelSlip
  duration: 5
  probability: 0.01

training:
  random_seed: 42
  epochs: 20
  batch_size: 64
  window_sizes: [5, 7, 10, 12, 15, 20, 25, 30]
  step_sizes: [1, 5, 7, 9]

inference:
  device: cpu
  batch_size: 64
  threshold_percentile: 99.95

model:
  input_size: 3
  hidden_dim: 8
  num_layers: 1

paths:
  default_output_file_csv: synthetic_dataset.csv
  model_save_path: src/core/models/best_model.pth
  log_dir: logs/fit
  training_data: data/training/train_Truck:80_360.csv
  validation_data: data/validation/val_Truck:80_360.csv
  testing_data: data/testing/test_Truck:80_360_WheelSlip:5:0.01.csv

endpoint_generate_dataset:
  summary: Synthetic dataset creation
  description: Generates synthetic time series according to the given parameters and outputs it as a CSV file.

endpoint_anomaly_detector:
  summary: Anomaly detection
  description: Detects anomalies in a time series. If no output parameter is given, it returns a list of time intervals, where the first timestamp indicates when the anomaly started, and the upper bound indicates when it stopped (not inclusive). If a filename is passed as a parameter, it outputs the results as a downloadable file.
