version: '3.9'

services:
  app:
    container_name: telemetry_service
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=.
    tty: true
    stdin_open: true