services:
  app:
    container_name: telemetry_service
    build:
      context: .
      dockerfile: src/Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=.
    tty: true
    stdin_open: true
  tests:
    container_name: telemetry_tests
    build:
      context: .
      dockerfile: src/Dockerfile
    working_dir: /app
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app